// Generated by engine/crates/ava1-gen from protocol/ava1/schema/ava1.toml. Do not edit:
// run `cargo run -p ava1-gen` from engine/ after changing the schema.
#![allow(clippy::field_reassign_with_default, clippy::single_match, clippy::match_single_binding)]

use crate::wire::{DecodeError, EncodeError, FrameMessage, Message, Reader, SplitMix, Writer};

pub const PROTOCOL_VERSION: u16 = 1;
pub const DEFAULT_PORT: u16 = 9120;
pub const MAX_LANES: u8 = 8;
pub const METHOD_NODE_INFO: u16 = 1;
pub const METHOD_PAIRING_OPEN: u16 = 2;
pub const METHOD_CRYPTO_BENCH: u16 = 3;
pub const STATUS_OK: u16 = 0;
pub const ERR_NOT_PAIRED: u16 = 1;
pub const ERR_PAIRING_CLOSED: u16 = 2;
pub const ERR_UNSUPPORTED_VERSION: u16 = 3;
pub const ERR_PROTOCOL: u16 = 4;
pub const ERR_BAD_JOIN: u16 = 5;
pub const ERR_UNKNOWN_METHOD: u16 = 6;
pub const ERR_INTERNAL: u16 = 7;
pub const ERR_BUSY: u16 = 8;

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Hs1 {
    pub noise: Vec<u8>,
}

impl Message for Hs1 {
    const NAME: &'static str = "Hs1";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.bytes(&self.noise)?;
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.noise = r.bytes()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

impl FrameMessage for Hs1 {
    const TYPE: u8 = 0x01;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Hs2 {
    pub noise: Vec<u8>,
}

impl Message for Hs2 {
    const NAME: &'static str = "Hs2";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.bytes(&self.noise)?;
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.noise = r.bytes()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

impl FrameMessage for Hs2 {
    const TYPE: u8 = 0x02;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Hs3 {
    pub noise: Vec<u8>,
}

impl Message for Hs3 {
    const NAME: &'static str = "Hs3";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.bytes(&self.noise)?;
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.noise = r.bytes()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

impl FrameMessage for Hs3 {
    const TYPE: u8 = 0x03;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Welcome {
    pub knows_you: u8,
}

impl Message for Welcome {
    const NAME: &'static str = "Welcome";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u8(self.knows_you);
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.knows_you = r.u8()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

impl FrameMessage for Welcome {
    const TYPE: u8 = 0x04;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct PairConfirm {
}

impl Message for PairConfirm {
    const NAME: &'static str = "PairConfirm";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let m = Self::default();
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

impl FrameMessage for PairConfirm {
    const TYPE: u8 = 0x05;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct PairResult {
    pub accepted: u8,
}

impl Message for PairResult {
    const NAME: &'static str = "PairResult";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u8(self.accepted);
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.accepted = r.u8()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

impl FrameMessage for PairResult {
    const TYPE: u8 = 0x06;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Join {
    pub session_id: [u8; 16],
    pub lane_id: u16,
    pub client_nonce: [u8; 16],
    pub tag: [u8; 16],
}

impl Message for Join {
    const NAME: &'static str = "Join";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.fixed(&self.session_id);
        w.u16(self.lane_id);
        w.fixed(&self.client_nonce);
        w.fixed(&self.tag);
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.session_id = r.fixed::<16>()?;
        m.lane_id = r.u16()?;
        m.client_nonce = r.fixed::<16>()?;
        m.tag = r.fixed::<16>()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

impl FrameMessage for Join {
    const TYPE: u8 = 0x07;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct JoinAck {
    pub lane_id: u16,
    pub server_nonce: [u8; 16],
    pub tag: [u8; 16],
}

impl Message for JoinAck {
    const NAME: &'static str = "JoinAck";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u16(self.lane_id);
        w.fixed(&self.server_nonce);
        w.fixed(&self.tag);
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.lane_id = r.u16()?;
        m.server_nonce = r.fixed::<16>()?;
        m.tag = r.fixed::<16>()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

impl FrameMessage for JoinAck {
    const TYPE: u8 = 0x08;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Ping {
    pub seq: u32,
    pub t_us: u64,
}

impl Message for Ping {
    const NAME: &'static str = "Ping";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u32(self.seq);
        w.u64(self.t_us);
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.seq = r.u32()?;
        m.t_us = r.u64()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

impl FrameMessage for Ping {
    const TYPE: u8 = 0x09;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Pong {
    pub seq: u32,
    pub t_us: u64,
}

impl Message for Pong {
    const NAME: &'static str = "Pong";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u32(self.seq);
        w.u64(self.t_us);
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.seq = r.u32()?;
        m.t_us = r.u64()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

impl FrameMessage for Pong {
    const TYPE: u8 = 0x0a;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Error {
    pub code: u16,
    pub message: String,
}

impl Message for Error {
    const NAME: &'static str = "Error";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u16(self.code);
        w.str(&self.message)?;
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.code = r.u16()?;
        m.message = r.str()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

impl FrameMessage for Error {
    const TYPE: u8 = 0x0b;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Bye {
    pub reason: u8,
}

impl Message for Bye {
    const NAME: &'static str = "Bye";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u8(self.reason);
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.reason = r.u8()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

impl FrameMessage for Bye {
    const TYPE: u8 = 0x0c;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct RpcRequest {
    pub method: u16,
    pub body: Vec<u8>,
}

impl Message for RpcRequest {
    const NAME: &'static str = "RpcRequest";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u16(self.method);
        w.bytes(&self.body)?;
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.method = r.u16()?;
        m.body = r.bytes()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

impl FrameMessage for RpcRequest {
    const TYPE: u8 = 0x60;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct RpcResponse {
    pub status: u16,
    pub body: Vec<u8>,
}

impl Message for RpcResponse {
    const NAME: &'static str = "RpcResponse";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u16(self.status);
        w.bytes(&self.body)?;
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.status = r.u16()?;
        m.body = r.bytes()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

impl FrameMessage for RpcResponse {
    const TYPE: u8 = 0x61;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct NodeInfo {
    pub version: String,
    pub platform: String,
    pub name: String,
    pub firmware: Option<String>,
}

impl Message for NodeInfo {
    const NAME: &'static str = "NodeInfo";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.str(&self.version)?;
        w.str(&self.platform)?;
        w.str(&self.name)?;
        let mut ext_n: u16 = 0;
        if self.firmware.is_some() { ext_n += 1; }
        w.u16(ext_n);
        if let Some(v) = &self.firmware { w.ext(1, |w| { w.str(v) })?; }
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.version = r.str()?;
        m.platform = r.str()?;
        m.name = r.str()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            match tag {
                1 => {
                    if m.firmware.is_some() { return Err(DecodeError::DupExt(1)); }
                    let mut vr = Reader::new(v);
                    m.firmware = Some(vr.str()?);
                    vr.finish()?;
                }
                _ => {}
            }
        }
        r.finish()?;
        Ok(m)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct HelloInfo {
    pub version_min: u16,
    pub version_max: u16,
    pub caps: u64,
}

impl Message for HelloInfo {
    const NAME: &'static str = "HelloInfo";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u16(self.version_min);
        w.u16(self.version_max);
        w.u64(self.caps);
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.version_min = r.u16()?;
        m.version_max = r.u16()?;
        m.caps = r.u64()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ServerInfo {
    pub version: u16,
    pub caps: u64,
    pub session_id: [u8; 16],
    pub name: Option<String>,
}

impl Message for ServerInfo {
    const NAME: &'static str = "ServerInfo";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u16(self.version);
        w.u64(self.caps);
        w.fixed(&self.session_id);
        let mut ext_n: u16 = 0;
        if self.name.is_some() { ext_n += 1; }
        w.u16(ext_n);
        if let Some(v) = &self.name { w.ext(1, |w| { w.str(v) })?; }
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.version = r.u16()?;
        m.caps = r.u64()?;
        m.session_id = r.fixed::<16>()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            match tag {
                1 => {
                    if m.name.is_some() { return Err(DecodeError::DupExt(1)); }
                    let mut vr = Reader::new(v);
                    m.name = Some(vr.str()?);
                    vr.finish()?;
                }
                _ => {}
            }
        }
        r.finish()?;
        Ok(m)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ClientInfo {
    pub name: Option<String>,
}

impl Message for ClientInfo {
    const NAME: &'static str = "ClientInfo";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        let mut ext_n: u16 = 0;
        if self.name.is_some() { ext_n += 1; }
        w.u16(ext_n);
        if let Some(v) = &self.name { w.ext(1, |w| { w.str(v) })?; }
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            match tag {
                1 => {
                    if m.name.is_some() { return Err(DecodeError::DupExt(1)); }
                    let mut vr = Reader::new(v);
                    m.name = Some(vr.str()?);
                    vr.finish()?;
                }
                _ => {}
            }
        }
        r.finish()?;
        Ok(m)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct PairingOpen {
    pub seconds: u16,
}

impl Message for PairingOpen {
    const NAME: &'static str = "PairingOpen";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u16(self.seconds);
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.seconds = r.u16()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct CryptoBench {
    pub mib: u16,
}

impl Message for CryptoBench {
    const NAME: &'static str = "CryptoBench";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u16(self.mib);
        w.u16(0);
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.mib = r.u16()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            let _ = (tag, v);
        }
        r.finish()?;
        Ok(m)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct CryptoBenchResult {
    pub bytes: u64,
    pub micros: u64,
    pub open_micros: Option<u64>,
    pub backend: Option<String>,
}

impl Message for CryptoBenchResult {
    const NAME: &'static str = "CryptoBenchResult";

    fn encode_into(&self, w: &mut Writer) -> Result<(), EncodeError> {
        w.u64(self.bytes);
        w.u64(self.micros);
        let mut ext_n: u16 = 0;
        if self.open_micros.is_some() { ext_n += 1; }
        if self.backend.is_some() { ext_n += 1; }
        w.u16(ext_n);
        if let Some(v) = &self.open_micros { w.ext(1, |w| { w.u64(*v); Ok(()) })?; }
        if let Some(v) = &self.backend { w.ext(2, |w| { w.str(v) })?; }
        Ok(())
    }

    fn decode(b: &[u8]) -> Result<Self, DecodeError> {
        let mut r = Reader::new(b);
        let mut m = Self::default();
        m.bytes = r.u64()?;
        m.micros = r.u64()?;
        let ext_n = r.u16()?;
        for _ in 0..ext_n {
            let tag = r.u16()?;
            let len = r.u32()? as usize;
            let v = r.take(len)?;
            match tag {
                1 => {
                    if m.open_micros.is_some() { return Err(DecodeError::DupExt(1)); }
                    let mut vr = Reader::new(v);
                    m.open_micros = Some(vr.u64()?);
                    vr.finish()?;
                }
                2 => {
                    if m.backend.is_some() { return Err(DecodeError::DupExt(2)); }
                    let mut vr = Reader::new(v);
                    m.backend = Some(vr.str()?);
                    vr.finish()?;
                }
                _ => {}
            }
        }
        r.finish()?;
        Ok(m)
    }
}

/// Every message and struct, by name (conformance tests).
pub const ALL: &[&str] = &["Hs1", "Hs2", "Hs3", "Welcome", "PairConfirm", "PairResult", "Join", "JoinAck", "Ping", "Pong", "Error", "Bye", "RpcRequest", "RpcResponse", "NodeInfo", "HelloInfo", "ServerInfo", "ClientInfo", "PairingOpen", "CryptoBench", "CryptoBenchResult", ];

#[doc(hidden)]
pub fn sample(name: &str, rng: &mut SplitMix) -> Option<Vec<u8>> {
    match name {
        "Hs1" => Hs1 { noise: { let n = rng.below(41) as usize; let mut v = vec![0u8; n]; rng.fill(&mut v); v }, }.to_bytes().ok(),
        "Hs2" => Hs2 { noise: { let n = rng.below(41) as usize; let mut v = vec![0u8; n]; rng.fill(&mut v); v }, }.to_bytes().ok(),
        "Hs3" => Hs3 { noise: { let n = rng.below(41) as usize; let mut v = vec![0u8; n]; rng.fill(&mut v); v }, }.to_bytes().ok(),
        "Welcome" => Welcome { knows_you: rng.next_u64() as u8, }.to_bytes().ok(),
        "PairConfirm" => PairConfirm { }.to_bytes().ok(),
        "PairResult" => PairResult { accepted: rng.next_u64() as u8, }.to_bytes().ok(),
        "Join" => Join { session_id: { let mut a = [0u8; 16]; rng.fill(&mut a); a }, lane_id: rng.next_u64() as u16, client_nonce: { let mut a = [0u8; 16]; rng.fill(&mut a); a }, tag: { let mut a = [0u8; 16]; rng.fill(&mut a); a }, }.to_bytes().ok(),
        "JoinAck" => JoinAck { lane_id: rng.next_u64() as u16, server_nonce: { let mut a = [0u8; 16]; rng.fill(&mut a); a }, tag: { let mut a = [0u8; 16]; rng.fill(&mut a); a }, }.to_bytes().ok(),
        "Ping" => Ping { seq: rng.next_u64() as u32, t_us: rng.next_u64(), }.to_bytes().ok(),
        "Pong" => Pong { seq: rng.next_u64() as u32, t_us: rng.next_u64(), }.to_bytes().ok(),
        "Error" => Error { code: rng.next_u64() as u16, message: rng.ascii(20), }.to_bytes().ok(),
        "Bye" => Bye { reason: rng.next_u64() as u8, }.to_bytes().ok(),
        "RpcRequest" => RpcRequest { method: rng.next_u64() as u16, body: { let n = rng.below(41) as usize; let mut v = vec![0u8; n]; rng.fill(&mut v); v }, }.to_bytes().ok(),
        "RpcResponse" => RpcResponse { status: rng.next_u64() as u16, body: { let n = rng.below(41) as usize; let mut v = vec![0u8; n]; rng.fill(&mut v); v }, }.to_bytes().ok(),
        "NodeInfo" => NodeInfo { version: rng.ascii(20), platform: rng.ascii(20), name: rng.ascii(20), firmware: if rng.below(2) == 1 { Some(rng.ascii(20)) } else { None }, }.to_bytes().ok(),
        "HelloInfo" => HelloInfo { version_min: rng.next_u64() as u16, version_max: rng.next_u64() as u16, caps: rng.next_u64(), }.to_bytes().ok(),
        "ServerInfo" => ServerInfo { version: rng.next_u64() as u16, caps: rng.next_u64(), session_id: { let mut a = [0u8; 16]; rng.fill(&mut a); a }, name: if rng.below(2) == 1 { Some(rng.ascii(20)) } else { None }, }.to_bytes().ok(),
        "ClientInfo" => ClientInfo { name: if rng.below(2) == 1 { Some(rng.ascii(20)) } else { None }, }.to_bytes().ok(),
        "PairingOpen" => PairingOpen { seconds: rng.next_u64() as u16, }.to_bytes().ok(),
        "CryptoBench" => CryptoBench { mib: rng.next_u64() as u16, }.to_bytes().ok(),
        "CryptoBenchResult" => CryptoBenchResult { bytes: rng.next_u64(), micros: rng.next_u64(), open_micros: if rng.below(2) == 1 { Some(rng.next_u64()) } else { None }, backend: if rng.below(2) == 1 { Some(rng.ascii(20)) } else { None }, }.to_bytes().ok(),
        _ => None,
    }
}

#[doc(hidden)]
pub fn roundtrip(name: &str, bytes: &[u8]) -> Option<Result<Vec<u8>, String>> {
    fn rt<M: Message>(b: &[u8]) -> Result<Vec<u8>, String> {
        M::decode(b).map_err(|e| e.to_string())?.to_bytes().map_err(|e| e.to_string())
    }
    Some(match name {
        "Hs1" => rt::<Hs1>(bytes),
        "Hs2" => rt::<Hs2>(bytes),
        "Hs3" => rt::<Hs3>(bytes),
        "Welcome" => rt::<Welcome>(bytes),
        "PairConfirm" => rt::<PairConfirm>(bytes),
        "PairResult" => rt::<PairResult>(bytes),
        "Join" => rt::<Join>(bytes),
        "JoinAck" => rt::<JoinAck>(bytes),
        "Ping" => rt::<Ping>(bytes),
        "Pong" => rt::<Pong>(bytes),
        "Error" => rt::<Error>(bytes),
        "Bye" => rt::<Bye>(bytes),
        "RpcRequest" => rt::<RpcRequest>(bytes),
        "RpcResponse" => rt::<RpcResponse>(bytes),
        "NodeInfo" => rt::<NodeInfo>(bytes),
        "HelloInfo" => rt::<HelloInfo>(bytes),
        "ServerInfo" => rt::<ServerInfo>(bytes),
        "ClientInfo" => rt::<ClientInfo>(bytes),
        "PairingOpen" => rt::<PairingOpen>(bytes),
        "CryptoBench" => rt::<CryptoBench>(bytes),
        "CryptoBenchResult" => rt::<CryptoBenchResult>(bytes),
        _ => return None,
    })
}
